package BaseTemplate.sandbox;

/*Generated by MPS */

import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.Files;
import java.nio.file.StandardOpenOption;
import java.io.IOException;

public class BaseTemplateGenerator {

  protected String folder = "";

  public void setFolder(String folder) {
    this.folder = folder;
  }

  public String getFolder() {
    return this.folder;
  }

  public void generate(String fileName, String contents) {
    Path path;
    if ((folder == null || folder.length() == 0)) {
      path = Paths.get(fileName);
    } else {
      path = Paths.get(folder, fileName);
    }
    try {
      Files.write(path, contents.getBytes(), StandardOpenOption.CREATE);
    } catch (IOException e) {
      e.printStackTrace();
    }
  }
}
