package BaseTemplate.behavior;

/*Generated by MPS */


public class TemplateResultLine {
  private StringBuilder text = new StringBuilder();
  private boolean hasNewline = false;

  public void append(String s) {
    this.text.append(s);
  }

  public void append(TemplateResultLine line) {
    this.text.append(line);
  }

  public void appendNewline() {
    this.hasNewline = true;
  }

  public boolean endOfLine() {
    return true;
  }

  @Override
  public String toString() {
    return (hasNewline ? text.toString() + "\n" : text.toString());
  }
}
