package BaseTemplate.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionAspectDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.HashMap;
import org.jetbrains.annotations.Nullable;
import java.util.Collection;
import org.jetbrains.annotations.NotNull;
import java.util.Arrays;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class IntentionsDescriptor extends AbstractIntentionAspectDescriptor {
  private static final IntentionFactory[] EMPTY_ARRAY = new IntentionFactory[0];
  private Map<SAbstractConcept, IntentionFactory[]> myCached = new HashMap<SAbstractConcept, IntentionFactory[]>();

  public IntentionsDescriptor() {
  }

  @Nullable
  public Collection<IntentionFactory> getIntentions(@NotNull SAbstractConcept concept) {
    if (myCached.containsKey(concept)) {
      return Arrays.asList(myCached.get(concept));
    }

    IntentionFactory[] intentions = EMPTY_ARRAY;
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        if (true) {
          // Concept: Indentable 
          intentions = new IntentionFactory[1];
          intentions[0] = new Indent_Intention();
        }
        break;
      case 1:
        if (true) {
          // Concept: TemplateForStatement 
          intentions = new IntentionFactory[3];
          intentions[0] = new AddStart_Intention();
          intentions[1] = new AddSeparator_Intention();
          intentions[2] = new AddEnd_Intention();
        }
        break;
      case 2:
        if (true) {
          // Concept: TemplateIfStatement 
          intentions = new IntentionFactory[2];
          intentions[0] = new Else_Intention();
          intentions[1] = new NoElse_Intention();
        }
        break;
      case 3:
        if (true) {
          // Concept: TemplateStatement 
          intentions = new IntentionFactory[1];
          intentions[0] = new CopyText_Intention();
        }
        break;
      case 4:
        if (true) {
          // Concept: TemplateStringWord 
          intentions = new IntentionFactory[1];
          intentions[0] = new InsertExpression_Intention();
        }
        break;
      case 5:
        if (true) {
          // Concept: TemplateTextStatement 
          intentions = new IntentionFactory[1];
          intentions[0] = new TemplateNewline_Intention();
        }
        break;
      default:
    }
    myCached.put(concept, intentions);
    return Arrays.asList(intentions);
  }

  @NotNull
  @Override
  public Collection<IntentionFactory> getAllIntentions() {
    IntentionFactory[] rv = new IntentionFactory[9];
    rv[0] = new InsertExpression_Intention();
    rv[1] = new Else_Intention();
    rv[2] = new NoElse_Intention();
    rv[3] = new CopyText_Intention();
    rv[4] = new TemplateNewline_Intention();
    rv[5] = new AddStart_Intention();
    rv[6] = new AddSeparator_Intention();
    rv[7] = new AddEnd_Intention();
    rv[8] = new Indent_Intention();
    return Arrays.asList(rv);
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xdb391f02128c4f99L, 0x939ab50794314dffL, 0x208c44dd6c78b53fL), MetaIdFactory.conceptId(0xdb391f02128c4f99L, 0x939ab50794314dffL, 0x6abb90ebe1739e4dL), MetaIdFactory.conceptId(0xdb391f02128c4f99L, 0x939ab50794314dffL, 0x6abb90ebe16d23bbL), MetaIdFactory.conceptId(0xdb391f02128c4f99L, 0x939ab50794314dffL, 0x6abb90ebe16d23baL), MetaIdFactory.conceptId(0xdb391f02128c4f99L, 0x939ab50794314dffL, 0x6abb90ebe165cb3fL), MetaIdFactory.conceptId(0xdb391f02128c4f99L, 0x939ab50794314dffL, 0x6abb90ebe165cb36L)).seal();
}
